/**
 * Generated by tsnapi — public API snapshot of `eslint-plugin-slop`
 */
// #region Interfaces
export interface SlopConfigOptions {
  cwd?: string;
  inspection?: SlopInspection;
  rules?: Partial<Record<SlopRuleId, Linter.RuleEntry>>;
}
export interface SlopSettings {
  cwd: string;
  inspection: SlopInspection;
}
// #endregion

// #region Types
export type SlopInspection = {
  mode: 'full';
} | {
  mode: 'uncommitted';
} | {
  mode: 'recent-changes';
  tracebackCommits?: number;
};
export type SlopRuleId = `slop/${SlopRuleName}`;
export type SlopRuleName = 'max-comment-length' | 'no-chained-type-assertions' | 'no-em-dash' | 'no-jargon' | 'no-trivial-functions' | 'no-trivial-type-aliases' | 'prefer-jsdoc';
// #endregion

// #region Functions
export declare function createSlopConfig(_?: SlopConfigOptions): Linter.Config[];
// #endregion

// #region Variables
export declare const defaultJargonWords: readonly ["utilize", "utilise", "leverage", "delve", "facilitate", "streamline", "seamless", "seamlessly", "robust", "comprehensive", "meticulous", "meticulously", "crucial", "pivotal", "myriad", "plethora", "paramount", "holistic", "multifaceted", "nuanced", "synergy", "bolster", "encompass", "endeavor", "endeavour", "aforementioned", "commence"];
export declare const rules: {
  'max-comment-length': import("eslint").Rule.RuleModule;
  'no-chained-type-assertions': import("eslint").Rule.RuleModule;
  'no-em-dash': import("eslint").Rule.RuleModule;
  'no-jargon': import("eslint").Rule.RuleModule;
  'no-trivial-functions': import("eslint").Rule.RuleModule;
  'no-trivial-type-aliases': import("eslint").Rule.RuleModule;
  'prefer-jsdoc': import("eslint").Rule.RuleModule;
};
// #endregion

// #region Default Export
declare const _default: ESLint.Plugin;
export default _default
// #endregion